CREATE TABLE [dbo].[Inventories] (
    [InventoryID]                           UNIQUEIDENTIFIER NOT NULL,
    [PurchaseOrderRequestID]                UNIQUEIDENTIFIER NULL,
    [NetworkCompanyID]                      UNIQUEIDENTIFIER NULL,
    [InventoryOtherSourceID]		        UNIQUEIDENTIFIER NULL,
    [CategoryID]                            UNIQUEIDENTIFIER NOT NULL,
    [ManufacturerID]                        UNIQUEIDENTIFIER NOT NULL,
    [ModelNumber]                           VARCHAR (100)    NULL,
    [Specifications]                        VARCHAR (MAX)    NULL,
    [WarrentyDate]                          DATETIME         NULL,
    [SerialNumber]                          VARCHAR (100)    NULL,
    [AssetTagNumber]                        VARCHAR (50)     NULL,
    [Issuable]                              BIT              NOT NULL,
    [CutOverStock]                          BIT              NULL,
    [AssetValue]                            MONEY            NOT NULL,
    [InsuranceRequired]                     BIT              NOT NULL,
    [AssetStatus]                           VARCHAR (50)     NOT NULL,
    [Remarks]                               VARCHAR (MAX)    NULL,
    [UserRequestNumber]                     VARCHAR (20)     NULL,
    [CreatedDate]                           DATETIME         NOT NULL,
    [CreatedBy]                             VARCHAR (200)    NOT NULL,
    [UpdatedDate]                           DATETIME         NOT NULL,
    [UpdatedBy]                             VARCHAR (200)    NOT NULL, 
    CONSTRAINT [PK_Inventories] PRIMARY KEY CLUSTERED ([InventoryID] ASC),
    CONSTRAINT [FK_Inventories_Categories] FOREIGN KEY ([CategoryID]) REFERENCES [dbo].[Categories] ([CategoryID]),
    CONSTRAINT [FK_Inventories_Manufacturers] FOREIGN KEY ([ManufacturerID]) REFERENCES [dbo].[Manufacturers] ([ManfacturerID]),
    CONSTRAINT [FK_Inventories_PurchaseOrderHeaders] FOREIGN KEY ([PurchaseOrderRequestID]) REFERENCES [dbo].[PurchaseOrderHeaders] ([PurchaseOrderRequestID])
);

