CREATE TABLE [dbo].[MaintenanceRequests]
(
	[RequestID]                                     UNIQUEIDENTIFIER NOT NULL, 
    [MaintenanceRequestNumber]                      VARCHAR(25)      NOT NULL UNIQUE, 
    [InventoryID]                                   UNIQUEIDENTIFIER NOT NULL, 
    [Priority]                                      VARCHAR(10)      NOT NULL, 
    [Status]                                        VARCHAR(20)      NOT NULL, 
    [SubStatus]                                     VARCHAR(50)      NULL, 
    [Description]                                   VARCHAR(MAX)     NOT NULL, 
    [Address]                                       VARCHAR(MAX)     NOT NULL, 
    [PhoneNumber]                                   VARCHAR(20)      NOT NULL, 
    [Remarks]                                       VARCHAR(MAX)     NULL, 
    [SubmittedDate]                                 DATETIME NOT     NULL, 
    [SubmittedBy]                                   VARCHAR(200)     NOT NULL, 
    [EmployeeName]                                  VARCHAR(200)     NOT NULL, 
    [ResolvedDate]                                  DATETIME         NULL,
    [FaultyAssetSentDate]                           DATETIME         NULL,
    [FaultyAssetReceivedDate]                       DATETIME         NULL,
    [RepairedAssetReceivedDate]                     DATETIME         NULL,
    [ReplacementAssetReceivedDate]                  DATETIME         NULL,
    [SupportCallTrackID]                            VARCHAR(25)      NULL,
    [SupportCallDate]                               DATETIME         NULL,
    [TargetDate]                                    DATETIME         NULL,
    [ReplacementAssetCourierProvider]               VARCHAR(20)      NULL,
    [ReplacementAssetCourierSentDate]               DATETIME         NULL,
    [ReplacementAssetCourierReference]              VARCHAR(30)      NULL,
    [RepairedAssetCourierProvider]                  VARCHAR(20)      NULL,
    [RepairedAssetCourierSentDate]                  DATETIME         NULL,
    [RepairedAssetCourierReference]                 VARCHAR(30)      NULL,
    [CreatedDate]                                   DATETIME         NOT NULL, 
    [CreatedBy]                                     VARCHAR(MAX)     NOT NULL, 
    [UpdatedDate]                                   DATETIME         NOT NULL, 
    [UpdatedBy]                                     VARCHAR(200)     NOT NULL,     
    CONSTRAINT [PK_MaintenanceRequests] PRIMARY KEY CLUSTERED ([RequestID] ASC),
     CONSTRAINT [FK_MaintenanceRequests_Inventories] FOREIGN KEY ([InventoryID]) REFERENCES [dbo].[Inventories] ([InventoryID])
);
