CREATE TABLE [dbo].[PurchaseRequests] (
    [RequestID]             UNIQUEIDENTIFIER NOT NULL,
    [PurchaseRequestNumber] VARCHAR (20)     NOT NULL UNIQUE,
    [NetworkCompanyID]      UNIQUEIDENTIFIER NOT NULL,
    [InventoryID]           UNIQUEIDENTIFIER NULL,
    [Purpose]               VARCHAR (MAX)    NOT NULL,
    [Status]                VARCHAR (15)     NOT NULL,
    [Comments]              VARCHAR (MAX)    NULL,
    [AdminComments]         VARCHAR (MAX)    NULL,
    [Active]                BIT              NOT NULL,
    [SubmittedOn]           DATETIME         NOT NULL,
    [SubmittedBy]           VARCHAR (200)    NOT NULL,
    [ApprovedOn]            DATETIME         NULL,
    [ApprovedBy]            VARCHAR (200)    NULL,
    [FullfilledOn]          DATETIME         NULL,
    [FullfilledBy]          VARCHAR (200)    NULL,
    [ITRequestNumber]       VARCHAR (50)     NULL,
    [CreatedDate]           DATETIME         NOT NULL,
    [CreatedBy]             VARCHAR (200)    NOT NULL,
    [UpdatedDate]           DATETIME         NOT NULL,
    [UpdatedBy]             VARCHAR (200)    NOT NULL,
    [ApproverName]          VARCHAR(200)     NULL, 
    [EmployeeName]          VARCHAR(200)     NULL, 
    [Priority]              VARCHAR(10)      NULL, 
    [CategoryId]            UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [PK_PurchaseRequests] PRIMARY KEY CLUSTERED ([RequestID] ASC),
    CONSTRAINT [FK_PurchaseRequests_NetworkCompanies] FOREIGN KEY ([NetworkCompanyID]) REFERENCES [dbo].[NetworkCompanies] ([NetworkCompanyID]),
    CONSTRAINT [FK_PurchaseRequests_Categories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories] ([CategoryID])
);

